config/routes.rb
Rails.application.routes.draw do
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root 'pages#home'
# No route matches [GET] "/about" get is the type of request /about is the route since this is a get request we can do the following
# simple static about page we can use  the pages controller that we made to handle the about action
get 'about', to: 'pages#about'
# now we have to create that in the views/pages and add it in the controller other wise we get an unknow action error from the controller as well as a template not found error in the views/pages no template found 

resources :blogs 



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true


end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/blog.rb
class Blog < ApplicationRecord

#review notes line 185 constraints
# the title is present for any blog to be saved
validates :title, presence: true, length: {minimum: 6, maximum: 100} 
# in the console this what will happen
# 2.6.1 :001 > blog = Blog.new
#    (0.5ms)  SELECT sqlite_version(*)
#  => #<Blog id: nil, title: nil, description: nil>
# 2.6.1 :002 > blog.save
#  => false 
# ----------------
# if we call erros this will be returned 
# blog.errors.full_messages
#  => ["Title can't be blank"] 

validates :description, presence: true, length: {minimum: 15, maximum: 300} 
# another validation we wanna add is uselessness of blogs so we can enforce minimum length requirment for title and description


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #hello action or method this needs a template
def hello 
    render html: "Hello rails"
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

# build the show action than we need a template
def index
@blogs = Blog.all
end

def show
    
@blog = Blog.find(params[:id])
end

def new 
@blog = Blog.new
end

def edit 
    @blog = Blog.find(params[:id])
end

def create


    
# render plain: params[:blog]
# rails extracts the attributes from the object using the id key
# we need to whitelist what is coming in from the web using strong params
@blog = Blog.new(params.require(:blog).permit(:title, :description))
# render plain: @blog.inspect

    if @blog.save
        flash[:notice] = "Blog created successfully"
# this will display a 204 on the console we have to tell rails where to go after this so we should redirect to the blogs show page
# redirect_to blogs_path this goes to index 
    redirect_to @blog
# redirect_to blogs_path(@blog)
# that will extract id from blog instance variable and take us to that url
# ------------------------------
# next step is to display error messages for the user to let them know that their entry are not valid in case they aren't
    else 

        render 'new'
    end
end




def update 
 
    @blog = Blog.find(params[:id])
  
    if @blog.update(params.require(:blog).permit(:title, :description))
     
        flash[:notice] = "Blog updated successfully"
        redirect_to blogs_path
       
    else 

        render 'edit'
    end
end

def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


def home 
end

def about
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/blogs/_form.html.erb

<%# form_with scope: ():our-model), submits to using (url:) than the path local will override the ajax functionality  %>
<% if @blog.errors.any? %>
<h2>The following errors prevented the blog of being saved </h2>
<ul>
<%@blog.errors.full_messages.each do |message|%>
    <li>
        <%=message%>
    </li>
</ul>
<%end%>
<%end%>
<%= form_with scope: :blog, url: blogs_path, local: true do |f|%>
<p> 
<%=f.label :title%><br>
<%=f.text_field :title%>
</p>

<p>
<%=f.label :description%><br>
<%=f.text_area :description, cols: "50", rows: "25"%>
</p>

<p>
<%=f.submit%>
<%end%>

app/views/blogs/edit.html.erb
<h1>Edit Blog</h1>


<%= form_with(model: @blog, local: true) do |f|%>
<p> 
<%=f.label :title%><br>
<%=f.text_field :title%>
</p>

<p>
<%=f.label :description%><br>
<%=f.text_area :description, cols: "50", rows: "25"%>
</p>

<p>
<%=f.submit%>
</p>
<%end%>

app/views/blogs/index.html.erb

<h1>Blogs link page</h1>
<h3>Click on article link to display that spesific link</h3>
<%@blogs.each do |blog|%>
<li>

<%=link_to blog.title, blog_path(blog.id)%> to delete click destroy
<button class="btn btn-danger">
<%= link_to  'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
</button>
</li>

<%end%>

app/views/blogs/new.html.erb
<h1>Create a new blog</h1>

<%=render 'form'%>

app/views/blogs/show.html.erb
<h3>Title: <%=@blog.title%>
<br><br>
description: <%=@blog.description%>
</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Doodles</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<%# this below is refering to stylesheet application in app/assets/stylesheets/application.css %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# below refering to app/packs/application.js %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%=link_to 'home', root_path%>
  <%# we can also say about_path %>
   <%=link_to 'about', 'about'  %>
   <%=link_to 'articles', '/articles'  %>
   <%=link_to 'create article', '/articles/new'%>
   <br><br><br>
   <h3>
   <%=link_to 'create blogs', '/blogs/new'%>
   </h3>
   <%flash.each do |name, msg|%>
   <%=msg%>
   <%end%>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1> This is the about page </h1>
<p> this is just a rails Doodles page, where i am practicing my skills creating websites</p>

<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit.<br> Odit placeat assumenda recusandae fugit sed cum dolore quae iusto beatae eum, minima ullam nisi numquam alias exercitationem optio quibusdam, ut perspiciatis.</p>
<ul>
<li>1. thank you for visiting</li>
<li>2. email me at aniss.marrouch@gmail.com</li>
</ul>

app/views/pages/home.html.erb
<h1>Welcome to Doodles</h1>